spring:
  application:
    name: books-api
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:books
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
